In [1]:
import pandas as pd

In [2]:
%%time
fpath = "/nfs/turbo/umms-indikar/shared/projects/czi_projects/metadata/all_metadata.parquet"
df = pd.read_parquet(fpath)
print(f"{df.shape=}")
df.head()

df.shape=(74322510, 28)
CPU times: user 31.7 s, sys: 20.5 s, total: 52.2 s
Wall time: 31.8 s

,soma_joinid,dataset_id,assay,assay_ontology_term_id,cell_type,cell_type_ontology_term_id,development_stage,development_stage_ontology_term_id,disease,disease_ontology_term_id,...,tissue,tissue_ontology_term_id,tissue_type,tissue_general,tissue_general_ontology_term_id,raw_sum,nnz,raw_mean_nnz,raw_variance_nnz,n_measured_vars
0,0,0895c838-e550-48a3-a777-dbcd35d30272,10x 3' v2,EFO:0009899,plasma cell,CL:0000786,human adult stage,HsapDv:0000087,normal,PATO:0000461,...,caudate lobe of liver,UBERON:0001117,tissue,liver,UBERON:0002107,1742.0,221,7.882353,6661.549733,13696
1,1,0895c838-e550-48a3-a777-dbcd35d30272,10x 3' v2,EFO:0009899,mature B cell,CL:0000785,human adult stage,HsapDv:0000087,normal,PATO:0000461,...,caudate lobe of liver,UBERON:0001117,tissue,liver,UBERON:0002107,278.0,143,1.944056,3.616567,13696
2,2,0895c838-e550-48a3-a777-dbcd35d30272,10x 3' v2,EFO:0009899,plasma cell,CL:0000786,human adult stage,HsapDv:0000087,normal,PATO:0000461,...,caudate lobe of liver,UBERON:0001117,tissue,liver,UBERON:0002107,3723.0,709,5.251058,2959.510327,13696
3,3,0895c838-e550-48a3-a777-dbcd35d30272,10x 3' v2,EFO:0009899,mature B cell,CL:0000785,human adult stage,HsapDv:0000087,normal,PATO:0000461,...,caudate lobe of liver,UBERON:0001117,tissue,liver,UBERON:0002107,351.0,179,1.960894,8.487226,13696
4,4,0895c838-e550-48a3-a777-dbcd35d30272,10x 3' v2,EFO:0009899,mature B cell,CL:0000785,human adult stage,HsapDv:0000087,normal,PATO:0000461,...,caudate lobe of liver,UBERON:0001117,tissue,liver,UBERON:0002107,605.0,275,2.200000,18.978102,13696

In [3]:
df.columns

Index(['soma_joinid', 'dataset_id', 'assay', 'assay_ontology_term_id',
       'cell_type', 'cell_type_ontology_term_id', 'development_stage',
       'development_stage_ontology_term_id', 'disease',
       'disease_ontology_term_id', 'donor_id', 'is_primary_data',
       'observation_joinid', 'self_reported_ethnicity',
       'self_reported_ethnicity_ontology_term_id', 'sex',
       'sex_ontology_term_id', 'suspension_type', 'tissue',
       'tissue_ontology_term_id', 'tissue_type', 'tissue_general',
       'tissue_general_ontology_term_id', 'raw_sum', 'nnz', 'raw_mean_nnz',
       'raw_variance_nnz', 'n_measured_vars'],
      dtype='object')

In [7]:
%time
outpath = "../../resources/dataset_ids.csv"
pdf = df.groupby('dataset_id')['soma_joinid'].count()
pdf = pdf.reset_index()
pdf.columns = ['dataset_id', 'n_cells']
print(f"{pdf.shape=}")
pdf.to_csv(outpath)
pdf.head()

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 7.63 µs

/tmp/ipykernel_2609158/1077661625.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  pdf = df.groupby('dataset_id')['soma_joinid'].count()

pdf.shape=(678, 2)

                             dataset_id  n_cells
0  0041b9c3-6a49-4bf7-8514-9bc7190067a7     9424
1  00476f9f-ebc1-4b72-b541-32f912ce36ea    10099
2  00e5dedd-b9b7-43be-8c28-b0e5c6414a62    21422
3  00ff600e-6e2e-4d76-846f-0eec4f0ae417      363
4  01209dce-3575-4bed-b1df-129f57fbc031    51876